language: ruby
cache: bundler

matrix:
  include:
    - rvm: 2.1.6
      env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes"
    - rvm: 2.2.6
      env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes"
    - rvm: 2.4.1
      env: PUPPET_VERSION="~> 5.0" STRICT_VARIABLES="yes"

script: 'bundle exec rake tests'

notifications:
  email:
    on_failure: change
    on_success: never
